version: '3.1'

services:
  mysql_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - '3307:3306'
    env_file:
      - './mysql.env'
    volumes:
      - './mysqlData:/var/lib/mysql'