version: '3.1'

services:
  mysql_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - '3307:3306'
    env_file:
      - './mysql.env'
    volumes:
      - './dbData/mysqlData:/var/lib/mysql'

  redis_db:
    image: redis:6.2.5-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./dbData/redisData:/data